package edu.njit.jerse.ashe.llm.google.models;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum GoogleModel {

    /**
     * Code Bison is a model from Google's Codey family of LLMs specific for code completion and generation
     */
    CODE_BISON(
            "code-bison",
            0.2,
            1000,
            1,
            0,
            0
    );

    /**
     * The identifier for the LLM
     */
    private final String model;

    /**
     * Controls the randomness of the output generated by a model.
     * A higher value increases the likelihood of the output being more random,
     * while a lower value makes it more deterministic.
     */
    private final double temperature;

    /**
     * The maximum length of the response in terms of tokens.
     * It limits the response length and can be used to manage response verbosity.
     */
    @JsonProperty("max_output_tokens")
    private final int maxOutputTokens;

    /**
     * The number of response variations that a model should return.
     * The acceptable range is from 1-4. For the purposes of ASHE, 1 should be sufficient.
     */
    @JsonProperty("candidate_count")
    private final int candidateCount;

    /**
     * Adjusts the likelihood of tokens appearing based on their frequency in the model's training data.
     * A negative value discourages the use of frequent tokens, while a positive value encourages their use.
     */
    @JsonProperty("frequency_penalty")
    private final int frequencyPenalty;

    /**
     * Adjusts the likelihood of tokens appearing based on their presence in the input message.
     * A positive value increases the likelihood of tokens appearing in the input to also appear in the output,
     * and vice versa.
     */
    @JsonProperty("presence_penalty")
    private final int presencePenalty;

    GoogleModel(String model, double temperature, int maxOutputTokens, int candidateCount, int frequencyPenalty, int presencePenalty) {
        this.model = model;
        this.temperature = temperature;
        this.maxOutputTokens = maxOutputTokens;
        this.candidateCount = candidateCount;
        this.frequencyPenalty = frequencyPenalty;
        this.presencePenalty = presencePenalty;
    }

    public String getModel() { return model; }

    public double getTemperature() { return temperature; }

    public int getMaxOutputTokens() { return maxOutputTokens; }

    public int getCandidateCount() { return candidateCount; }

    public int getFrequencyPenalty() { return frequencyPenalty; }

    public int getPresencePenalty() { return presencePenalty; }
}
